// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/agent/proto/switch_agent.proto

package switchagentproto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwitchAgentService_GetDeviceInfo_FullMethodName           = "/switchagent.v1.SwitchAgentService/GetDeviceInfo"
	SwitchAgentService_ListInterfaces_FullMethodName          = "/switchagent.v1.SwitchAgentService/ListInterfaces"
	SwitchAgentService_SetInterfaceAdminStatus_FullMethodName = "/switchagent.v1.SwitchAgentService/SetInterfaceAdminStatus"
	SwitchAgentService_SetInterfaceAliasName_FullMethodName   = "/switchagent.v1.SwitchAgentService/SetInterfaceAliasName"
	SwitchAgentService_GetInterface_FullMethodName            = "/switchagent.v1.SwitchAgentService/GetInterface"
	SwitchAgentService_GetInterfaceNeighbor_FullMethodName    = "/switchagent.v1.SwitchAgentService/GetInterfaceNeighbor"
	SwitchAgentService_ListPorts_FullMethodName               = "/switchagent.v1.SwitchAgentService/ListPorts"
	SwitchAgentService_SaveConfig_FullMethodName              = "/switchagent.v1.SwitchAgentService/SaveConfig"
	SwitchAgentService_Reboot_FullMethodName                  = "/switchagent.v1.SwitchAgentService/Reboot"
	SwitchAgentService_OnieBootModeInstall_FullMethodName     = "/switchagent.v1.SwitchAgentService/OnieBootModeInstall"
	SwitchAgentService_RestartSystemdService_FullMethodName   = "/switchagent.v1.SwitchAgentService/RestartSystemdService"
	SwitchAgentService_RebootCause_FullMethodName             = "/switchagent.v1.SwitchAgentService/RebootCause"
	SwitchAgentService_FactoryReset_FullMethodName            = "/switchagent.v1.SwitchAgentService/FactoryReset"
	SwitchAgentService_GetReadiness_FullMethodName            = "/switchagent.v1.SwitchAgentService/GetReadiness"
)

// SwitchAgentServiceClient is the client API for SwitchAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The interface service definition.
type SwitchAgentServiceClient interface {
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error)
	ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error)
	SetInterfaceAdminStatus(ctx context.Context, in *SetInterfaceAdminStatusRequest, opts ...grpc.CallOption) (*SetInterfaceAdminStatusResponse, error)
	SetInterfaceAliasName(ctx context.Context, in *SetInterfaceAliasNameRequest, opts ...grpc.CallOption) (*SetInterfaceAliasNameResponse, error)
	GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceResponse, error)
	GetInterfaceNeighbor(ctx context.Context, in *GetInterfaceNeighborRequest, opts ...grpc.CallOption) (*GetInterfaceNeighborResponse, error)
	ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error)
	// gNOI alternatives
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error)
	OnieBootModeInstall(ctx context.Context, in *OnieBootModeInstallRequest, opts ...grpc.CallOption) (*OnieBootModeInstallResponse, error)
	RestartSystemdService(ctx context.Context, in *RestartSystemdServiceRequest, opts ...grpc.CallOption) (*RestartSystemdServiceResponse, error)
	RebootCause(ctx context.Context, in *RebootCauseRequest, opts ...grpc.CallOption) (*RebootCauseResponse, error)
	FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error)
	GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessResponse, error)
}

type switchAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchAgentServiceClient(cc grpc.ClientConnInterface) SwitchAgentServiceClient {
	return &switchAgentServiceClient{cc}
}

func (c *switchAgentServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*GetDeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) ListInterfaces(ctx context.Context, in *ListInterfacesRequest, opts ...grpc.CallOption) (*ListInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_ListInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SetInterfaceAdminStatus(ctx context.Context, in *SetInterfaceAdminStatusRequest, opts ...grpc.CallOption) (*SetInterfaceAdminStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInterfaceAdminStatusResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SetInterfaceAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SetInterfaceAliasName(ctx context.Context, in *SetInterfaceAliasNameRequest, opts ...grpc.CallOption) (*SetInterfaceAliasNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInterfaceAliasNameResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SetInterfaceAliasName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetInterface(ctx context.Context, in *GetInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetInterfaceNeighbor(ctx context.Context, in *GetInterfaceNeighborRequest, opts ...grpc.CallOption) (*GetInterfaceNeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceNeighborResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetInterfaceNeighbor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) ListPorts(ctx context.Context, in *ListPortsRequest, opts ...grpc.CallOption) (*ListPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortsResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_SaveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*RebootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebootResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) OnieBootModeInstall(ctx context.Context, in *OnieBootModeInstallRequest, opts ...grpc.CallOption) (*OnieBootModeInstallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnieBootModeInstallResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_OnieBootModeInstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) RestartSystemdService(ctx context.Context, in *RestartSystemdServiceRequest, opts ...grpc.CallOption) (*RestartSystemdServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartSystemdServiceResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_RestartSystemdService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) RebootCause(ctx context.Context, in *RebootCauseRequest, opts ...grpc.CallOption) (*RebootCauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebootCauseResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_RebootCause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactoryResetResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_FactoryReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *switchAgentServiceClient) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadinessResponse)
	err := c.cc.Invoke(ctx, SwitchAgentService_GetReadiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchAgentServiceServer is the server API for SwitchAgentService service.
// All implementations must embed UnimplementedSwitchAgentServiceServer
// for forward compatibility.
//
// The interface service definition.
type SwitchAgentServiceServer interface {
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error)
	ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error)
	SetInterfaceAdminStatus(context.Context, *SetInterfaceAdminStatusRequest) (*SetInterfaceAdminStatusResponse, error)
	SetInterfaceAliasName(context.Context, *SetInterfaceAliasNameRequest) (*SetInterfaceAliasNameResponse, error)
	GetInterface(context.Context, *GetInterfaceRequest) (*GetInterfaceResponse, error)
	GetInterfaceNeighbor(context.Context, *GetInterfaceNeighborRequest) (*GetInterfaceNeighborResponse, error)
	ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error)
	// gNOI alternatives
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	Reboot(context.Context, *RebootRequest) (*RebootResponse, error)
	OnieBootModeInstall(context.Context, *OnieBootModeInstallRequest) (*OnieBootModeInstallResponse, error)
	RestartSystemdService(context.Context, *RestartSystemdServiceRequest) (*RestartSystemdServiceResponse, error)
	RebootCause(context.Context, *RebootCauseRequest) (*RebootCauseResponse, error)
	FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error)
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

// UnimplementedSwitchAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwitchAgentServiceServer struct{}

func (UnimplementedSwitchAgentServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*GetDeviceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedSwitchAgentServiceServer) ListInterfaces(context.Context, *ListInterfacesRequest) (*ListInterfacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SetInterfaceAdminStatus(context.Context, *SetInterfaceAdminStatusRequest) (*SetInterfaceAdminStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterfaceAdminStatus not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SetInterfaceAliasName(context.Context, *SetInterfaceAliasNameRequest) (*SetInterfaceAliasNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterfaceAliasName not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetInterface(context.Context, *GetInterfaceRequest) (*GetInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetInterfaceNeighbor(context.Context, *GetInterfaceNeighborRequest) (*GetInterfaceNeighborResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaceNeighbor not implemented")
}
func (UnimplementedSwitchAgentServiceServer) ListPorts(context.Context, *ListPortsRequest) (*ListPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedSwitchAgentServiceServer) SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedSwitchAgentServiceServer) Reboot(context.Context, *RebootRequest) (*RebootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedSwitchAgentServiceServer) OnieBootModeInstall(context.Context, *OnieBootModeInstallRequest) (*OnieBootModeInstallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnieBootModeInstall not implemented")
}
func (UnimplementedSwitchAgentServiceServer) RestartSystemdService(context.Context, *RestartSystemdServiceRequest) (*RestartSystemdServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartSystemdService not implemented")
}
func (UnimplementedSwitchAgentServiceServer) RebootCause(context.Context, *RebootCauseRequest) (*RebootCauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebootCause not implemented")
}
func (UnimplementedSwitchAgentServiceServer) FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactoryReset not implemented")
}
func (UnimplementedSwitchAgentServiceServer) GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadiness not implemented")
}
func (UnimplementedSwitchAgentServiceServer) mustEmbedUnimplementedSwitchAgentServiceServer() {}
func (UnimplementedSwitchAgentServiceServer) testEmbeddedByValue()                            {}

// UnsafeSwitchAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchAgentServiceServer will
// result in compilation errors.
type UnsafeSwitchAgentServiceServer interface {
	mustEmbedUnimplementedSwitchAgentServiceServer()
}

func RegisterSwitchAgentServiceServer(s grpc.ServiceRegistrar, srv SwitchAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedSwitchAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwitchAgentService_ServiceDesc, srv)
}

func _SwitchAgentService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_ListInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).ListInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_ListInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).ListInterfaces(ctx, req.(*ListInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SetInterfaceAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInterfaceAdminStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SetInterfaceAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SetInterfaceAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SetInterfaceAdminStatus(ctx, req.(*SetInterfaceAdminStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SetInterfaceAliasName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInterfaceAliasNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SetInterfaceAliasName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SetInterfaceAliasName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SetInterfaceAliasName(ctx, req.(*SetInterfaceAliasNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetInterface(ctx, req.(*GetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetInterfaceNeighbor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfaceNeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetInterfaceNeighbor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetInterfaceNeighbor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetInterfaceNeighbor(ctx, req.(*GetInterfaceNeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).ListPorts(ctx, req.(*ListPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_SaveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).Reboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_OnieBootModeInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnieBootModeInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).OnieBootModeInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_OnieBootModeInstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).OnieBootModeInstall(ctx, req.(*OnieBootModeInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_RestartSystemdService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartSystemdServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).RestartSystemdService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_RestartSystemdService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).RestartSystemdService(ctx, req.(*RestartSystemdServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_RebootCause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootCauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).RebootCause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_RebootCause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).RebootCause(ctx, req.(*RebootCauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_FactoryReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).FactoryReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_FactoryReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).FactoryReset(ctx, req.(*FactoryResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwitchAgentService_GetReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchAgentServiceServer).GetReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwitchAgentService_GetReadiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchAgentServiceServer).GetReadiness(ctx, req.(*GetReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwitchAgentService_ServiceDesc is the grpc.ServiceDesc for SwitchAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.SwitchAgentService",
	HandlerType: (*SwitchAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _SwitchAgentService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "ListInterfaces",
			Handler:    _SwitchAgentService_ListInterfaces_Handler,
		},
		{
			MethodName: "SetInterfaceAdminStatus",
			Handler:    _SwitchAgentService_SetInterfaceAdminStatus_Handler,
		},
		{
			MethodName: "SetInterfaceAliasName",
			Handler:    _SwitchAgentService_SetInterfaceAliasName_Handler,
		},
		{
			MethodName: "GetInterface",
			Handler:    _SwitchAgentService_GetInterface_Handler,
		},
		{
			MethodName: "GetInterfaceNeighbor",
			Handler:    _SwitchAgentService_GetInterfaceNeighbor_Handler,
		},
		{
			MethodName: "ListPorts",
			Handler:    _SwitchAgentService_ListPorts_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _SwitchAgentService_SaveConfig_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _SwitchAgentService_Reboot_Handler,
		},
		{
			MethodName: "OnieBootModeInstall",
			Handler:    _SwitchAgentService_OnieBootModeInstall_Handler,
		},
		{
			MethodName: "RestartSystemdService",
			Handler:    _SwitchAgentService_RestartSystemdService_Handler,
		},
		{
			MethodName: "RebootCause",
			Handler:    _SwitchAgentService_RebootCause_Handler,
		},
		{
			MethodName: "FactoryReset",
			Handler:    _SwitchAgentService_FactoryReset_Handler,
		},
		{
			MethodName: "GetReadiness",
			Handler:    _SwitchAgentService_GetReadiness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}

const (
	DeviceProviderService_ListPorts_FullMethodName         = "/switchagent.v1.DeviceProviderService/ListPorts"
	DeviceProviderService_GetDeviceInfo_FullMethodName     = "/switchagent.v1.DeviceProviderService/GetDeviceInfo"
	DeviceProviderService_GetLastRebootTime_FullMethodName = "/switchagent.v1.DeviceProviderService/GetLastRebootTime"
	DeviceProviderService_Reboot_FullMethodName            = "/switchagent.v1.DeviceProviderService/Reboot"
	DeviceProviderService_FactoryReset_FullMethodName      = "/switchagent.v1.DeviceProviderService/FactoryReset"
	DeviceProviderService_Reprovision_FullMethodName       = "/switchagent.v1.DeviceProviderService/Reprovision"
)

// DeviceProviderServiceClient is the client API for DeviceProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceProviderServiceClient interface {
	ListPorts(ctx context.Context, in *DeviceProviderListPortsRequest, opts ...grpc.CallOption) (*DeviceProviderListPortsResponse, error)
	GetDeviceInfo(ctx context.Context, in *DeviceProviderGetDeviceInfoRequest, opts ...grpc.CallOption) (*DeviceProviderGetDeviceInfoResponse, error)
	GetLastRebootTime(ctx context.Context, in *DeviceProviderGetLastRebootTimeRequest, opts ...grpc.CallOption) (*DeviceProviderGetLastRebootTimeResponse, error)
	Reboot(ctx context.Context, in *DeviceProviderRebootRequest, opts ...grpc.CallOption) (*DeviceProviderRebootResponse, error)
	FactoryReset(ctx context.Context, in *DeviceProviderFactoryResetRequest, opts ...grpc.CallOption) (*DeviceProviderFactoryResetResponse, error)
	Reprovision(ctx context.Context, in *DeviceProviderReprovisionRequest, opts ...grpc.CallOption) (*DeviceProviderReprovisionResponse, error)
}

type deviceProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceProviderServiceClient(cc grpc.ClientConnInterface) DeviceProviderServiceClient {
	return &deviceProviderServiceClient{cc}
}

func (c *deviceProviderServiceClient) ListPorts(ctx context.Context, in *DeviceProviderListPortsRequest, opts ...grpc.CallOption) (*DeviceProviderListPortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceProviderListPortsResponse)
	err := c.cc.Invoke(ctx, DeviceProviderService_ListPorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceProviderServiceClient) GetDeviceInfo(ctx context.Context, in *DeviceProviderGetDeviceInfoRequest, opts ...grpc.CallOption) (*DeviceProviderGetDeviceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceProviderGetDeviceInfoResponse)
	err := c.cc.Invoke(ctx, DeviceProviderService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceProviderServiceClient) GetLastRebootTime(ctx context.Context, in *DeviceProviderGetLastRebootTimeRequest, opts ...grpc.CallOption) (*DeviceProviderGetLastRebootTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceProviderGetLastRebootTimeResponse)
	err := c.cc.Invoke(ctx, DeviceProviderService_GetLastRebootTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceProviderServiceClient) Reboot(ctx context.Context, in *DeviceProviderRebootRequest, opts ...grpc.CallOption) (*DeviceProviderRebootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceProviderRebootResponse)
	err := c.cc.Invoke(ctx, DeviceProviderService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceProviderServiceClient) FactoryReset(ctx context.Context, in *DeviceProviderFactoryResetRequest, opts ...grpc.CallOption) (*DeviceProviderFactoryResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceProviderFactoryResetResponse)
	err := c.cc.Invoke(ctx, DeviceProviderService_FactoryReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceProviderServiceClient) Reprovision(ctx context.Context, in *DeviceProviderReprovisionRequest, opts ...grpc.CallOption) (*DeviceProviderReprovisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceProviderReprovisionResponse)
	err := c.cc.Invoke(ctx, DeviceProviderService_Reprovision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceProviderServiceServer is the server API for DeviceProviderService service.
// All implementations must embed UnimplementedDeviceProviderServiceServer
// for forward compatibility.
type DeviceProviderServiceServer interface {
	ListPorts(context.Context, *DeviceProviderListPortsRequest) (*DeviceProviderListPortsResponse, error)
	GetDeviceInfo(context.Context, *DeviceProviderGetDeviceInfoRequest) (*DeviceProviderGetDeviceInfoResponse, error)
	GetLastRebootTime(context.Context, *DeviceProviderGetLastRebootTimeRequest) (*DeviceProviderGetLastRebootTimeResponse, error)
	Reboot(context.Context, *DeviceProviderRebootRequest) (*DeviceProviderRebootResponse, error)
	FactoryReset(context.Context, *DeviceProviderFactoryResetRequest) (*DeviceProviderFactoryResetResponse, error)
	Reprovision(context.Context, *DeviceProviderReprovisionRequest) (*DeviceProviderReprovisionResponse, error)
	mustEmbedUnimplementedDeviceProviderServiceServer()
}

// UnimplementedDeviceProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceProviderServiceServer struct{}

func (UnimplementedDeviceProviderServiceServer) ListPorts(context.Context, *DeviceProviderListPortsRequest) (*DeviceProviderListPortsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPorts not implemented")
}
func (UnimplementedDeviceProviderServiceServer) GetDeviceInfo(context.Context, *DeviceProviderGetDeviceInfoRequest) (*DeviceProviderGetDeviceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedDeviceProviderServiceServer) GetLastRebootTime(context.Context, *DeviceProviderGetLastRebootTimeRequest) (*DeviceProviderGetLastRebootTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastRebootTime not implemented")
}
func (UnimplementedDeviceProviderServiceServer) Reboot(context.Context, *DeviceProviderRebootRequest) (*DeviceProviderRebootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedDeviceProviderServiceServer) FactoryReset(context.Context, *DeviceProviderFactoryResetRequest) (*DeviceProviderFactoryResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactoryReset not implemented")
}
func (UnimplementedDeviceProviderServiceServer) Reprovision(context.Context, *DeviceProviderReprovisionRequest) (*DeviceProviderReprovisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reprovision not implemented")
}
func (UnimplementedDeviceProviderServiceServer) mustEmbedUnimplementedDeviceProviderServiceServer() {}
func (UnimplementedDeviceProviderServiceServer) testEmbeddedByValue()                               {}

// UnsafeDeviceProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceProviderServiceServer will
// result in compilation errors.
type UnsafeDeviceProviderServiceServer interface {
	mustEmbedUnimplementedDeviceProviderServiceServer()
}

func RegisterDeviceProviderServiceServer(s grpc.ServiceRegistrar, srv DeviceProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceProviderService_ServiceDesc, srv)
}

func _DeviceProviderService_ListPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceProviderListPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceProviderServiceServer).ListPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceProviderService_ListPorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceProviderServiceServer).ListPorts(ctx, req.(*DeviceProviderListPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceProviderService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceProviderGetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceProviderServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceProviderService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceProviderServiceServer).GetDeviceInfo(ctx, req.(*DeviceProviderGetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceProviderService_GetLastRebootTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceProviderGetLastRebootTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceProviderServiceServer).GetLastRebootTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceProviderService_GetLastRebootTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceProviderServiceServer).GetLastRebootTime(ctx, req.(*DeviceProviderGetLastRebootTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceProviderService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceProviderRebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceProviderServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceProviderService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceProviderServiceServer).Reboot(ctx, req.(*DeviceProviderRebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceProviderService_FactoryReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceProviderFactoryResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceProviderServiceServer).FactoryReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceProviderService_FactoryReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceProviderServiceServer).FactoryReset(ctx, req.(*DeviceProviderFactoryResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceProviderService_Reprovision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceProviderReprovisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceProviderServiceServer).Reprovision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceProviderService_Reprovision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceProviderServiceServer).Reprovision(ctx, req.(*DeviceProviderReprovisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceProviderService_ServiceDesc is the grpc.ServiceDesc for DeviceProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.DeviceProviderService",
	HandlerType: (*DeviceProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPorts",
			Handler:    _DeviceProviderService_ListPorts_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _DeviceProviderService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "GetLastRebootTime",
			Handler:    _DeviceProviderService_GetLastRebootTime_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _DeviceProviderService_Reboot_Handler,
		},
		{
			MethodName: "FactoryReset",
			Handler:    _DeviceProviderService_FactoryReset_Handler,
		},
		{
			MethodName: "Reprovision",
			Handler:    _DeviceProviderService_Reprovision_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}

const (
	InterfaceProviderService_EnsureInterface_FullMethodName    = "/switchagent.v1.InterfaceProviderService/EnsureInterface"
	InterfaceProviderService_DeleteInterface_FullMethodName    = "/switchagent.v1.InterfaceProviderService/DeleteInterface"
	InterfaceProviderService_GetInterfaceStatus_FullMethodName = "/switchagent.v1.InterfaceProviderService/GetInterfaceStatus"
)

// InterfaceProviderServiceClient is the client API for InterfaceProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterfaceProviderServiceClient interface {
	EnsureInterface(ctx context.Context, in *EnsureInterfaceRequest, opts ...grpc.CallOption) (*EnsureInterfaceResponse, error)
	DeleteInterface(ctx context.Context, in *InterfaceProviderInterfaceRequest, opts ...grpc.CallOption) (*DeleteInterfaceResponse, error)
	GetInterfaceStatus(ctx context.Context, in *InterfaceProviderInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceStatusResponse, error)
}

type interfaceProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterfaceProviderServiceClient(cc grpc.ClientConnInterface) InterfaceProviderServiceClient {
	return &interfaceProviderServiceClient{cc}
}

func (c *interfaceProviderServiceClient) EnsureInterface(ctx context.Context, in *EnsureInterfaceRequest, opts ...grpc.CallOption) (*EnsureInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureInterfaceResponse)
	err := c.cc.Invoke(ctx, InterfaceProviderService_EnsureInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceProviderServiceClient) DeleteInterface(ctx context.Context, in *InterfaceProviderInterfaceRequest, opts ...grpc.CallOption) (*DeleteInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInterfaceResponse)
	err := c.cc.Invoke(ctx, InterfaceProviderService_DeleteInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interfaceProviderServiceClient) GetInterfaceStatus(ctx context.Context, in *InterfaceProviderInterfaceRequest, opts ...grpc.CallOption) (*GetInterfaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterfaceStatusResponse)
	err := c.cc.Invoke(ctx, InterfaceProviderService_GetInterfaceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterfaceProviderServiceServer is the server API for InterfaceProviderService service.
// All implementations must embed UnimplementedInterfaceProviderServiceServer
// for forward compatibility.
type InterfaceProviderServiceServer interface {
	EnsureInterface(context.Context, *EnsureInterfaceRequest) (*EnsureInterfaceResponse, error)
	DeleteInterface(context.Context, *InterfaceProviderInterfaceRequest) (*DeleteInterfaceResponse, error)
	GetInterfaceStatus(context.Context, *InterfaceProviderInterfaceRequest) (*GetInterfaceStatusResponse, error)
	mustEmbedUnimplementedInterfaceProviderServiceServer()
}

// UnimplementedInterfaceProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterfaceProviderServiceServer struct{}

func (UnimplementedInterfaceProviderServiceServer) EnsureInterface(context.Context, *EnsureInterfaceRequest) (*EnsureInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureInterface not implemented")
}
func (UnimplementedInterfaceProviderServiceServer) DeleteInterface(context.Context, *InterfaceProviderInterfaceRequest) (*DeleteInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInterface not implemented")
}
func (UnimplementedInterfaceProviderServiceServer) GetInterfaceStatus(context.Context, *InterfaceProviderInterfaceRequest) (*GetInterfaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaceStatus not implemented")
}
func (UnimplementedInterfaceProviderServiceServer) mustEmbedUnimplementedInterfaceProviderServiceServer() {
}
func (UnimplementedInterfaceProviderServiceServer) testEmbeddedByValue() {}

// UnsafeInterfaceProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterfaceProviderServiceServer will
// result in compilation errors.
type UnsafeInterfaceProviderServiceServer interface {
	mustEmbedUnimplementedInterfaceProviderServiceServer()
}

func RegisterInterfaceProviderServiceServer(s grpc.ServiceRegistrar, srv InterfaceProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedInterfaceProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterfaceProviderService_ServiceDesc, srv)
}

func _InterfaceProviderService_EnsureInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceProviderServiceServer).EnsureInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceProviderService_EnsureInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceProviderServiceServer).EnsureInterface(ctx, req.(*EnsureInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceProviderService_DeleteInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceProviderInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceProviderServiceServer).DeleteInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceProviderService_DeleteInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceProviderServiceServer).DeleteInterface(ctx, req.(*InterfaceProviderInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterfaceProviderService_GetInterfaceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceProviderInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterfaceProviderServiceServer).GetInterfaceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterfaceProviderService_GetInterfaceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterfaceProviderServiceServer).GetInterfaceStatus(ctx, req.(*InterfaceProviderInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterfaceProviderService_ServiceDesc is the grpc.ServiceDesc for InterfaceProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterfaceProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.InterfaceProviderService",
	HandlerType: (*InterfaceProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureInterface",
			Handler:    _InterfaceProviderService_EnsureInterface_Handler,
		},
		{
			MethodName: "DeleteInterface",
			Handler:    _InterfaceProviderService_DeleteInterface_Handler,
		},
		{
			MethodName: "GetInterfaceStatus",
			Handler:    _InterfaceProviderService_GetInterfaceStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}

const (
	DHCPRelayProviderService_EnsureDHCPRelay_FullMethodName    = "/switchagent.v1.DHCPRelayProviderService/EnsureDHCPRelay"
	DHCPRelayProviderService_DeleteDHCPRelay_FullMethodName    = "/switchagent.v1.DHCPRelayProviderService/DeleteDHCPRelay"
	DHCPRelayProviderService_GetDHCPRelayStatus_FullMethodName = "/switchagent.v1.DHCPRelayProviderService/GetDHCPRelayStatus"
)

// DHCPRelayProviderServiceClient is the client API for DHCPRelayProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DHCPRelayProviderServiceClient interface {
	EnsureDHCPRelay(ctx context.Context, in *DHCPRelayProviderEnsureRequest, opts ...grpc.CallOption) (*DHCPRelayProviderEnsureResponse, error)
	DeleteDHCPRelay(ctx context.Context, in *DHCPRelayProviderDeleteRequest, opts ...grpc.CallOption) (*DHCPRelayProviderDeleteResponse, error)
	GetDHCPRelayStatus(ctx context.Context, in *DHCPRelayProviderGetStatusRequest, opts ...grpc.CallOption) (*DHCPRelayProviderGetStatusResponse, error)
}

type dHCPRelayProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDHCPRelayProviderServiceClient(cc grpc.ClientConnInterface) DHCPRelayProviderServiceClient {
	return &dHCPRelayProviderServiceClient{cc}
}

func (c *dHCPRelayProviderServiceClient) EnsureDHCPRelay(ctx context.Context, in *DHCPRelayProviderEnsureRequest, opts ...grpc.CallOption) (*DHCPRelayProviderEnsureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DHCPRelayProviderEnsureResponse)
	err := c.cc.Invoke(ctx, DHCPRelayProviderService_EnsureDHCPRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHCPRelayProviderServiceClient) DeleteDHCPRelay(ctx context.Context, in *DHCPRelayProviderDeleteRequest, opts ...grpc.CallOption) (*DHCPRelayProviderDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DHCPRelayProviderDeleteResponse)
	err := c.cc.Invoke(ctx, DHCPRelayProviderService_DeleteDHCPRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHCPRelayProviderServiceClient) GetDHCPRelayStatus(ctx context.Context, in *DHCPRelayProviderGetStatusRequest, opts ...grpc.CallOption) (*DHCPRelayProviderGetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DHCPRelayProviderGetStatusResponse)
	err := c.cc.Invoke(ctx, DHCPRelayProviderService_GetDHCPRelayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DHCPRelayProviderServiceServer is the server API for DHCPRelayProviderService service.
// All implementations must embed UnimplementedDHCPRelayProviderServiceServer
// for forward compatibility.
type DHCPRelayProviderServiceServer interface {
	EnsureDHCPRelay(context.Context, *DHCPRelayProviderEnsureRequest) (*DHCPRelayProviderEnsureResponse, error)
	DeleteDHCPRelay(context.Context, *DHCPRelayProviderDeleteRequest) (*DHCPRelayProviderDeleteResponse, error)
	GetDHCPRelayStatus(context.Context, *DHCPRelayProviderGetStatusRequest) (*DHCPRelayProviderGetStatusResponse, error)
	mustEmbedUnimplementedDHCPRelayProviderServiceServer()
}

// UnimplementedDHCPRelayProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDHCPRelayProviderServiceServer struct{}

func (UnimplementedDHCPRelayProviderServiceServer) EnsureDHCPRelay(context.Context, *DHCPRelayProviderEnsureRequest) (*DHCPRelayProviderEnsureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureDHCPRelay not implemented")
}
func (UnimplementedDHCPRelayProviderServiceServer) DeleteDHCPRelay(context.Context, *DHCPRelayProviderDeleteRequest) (*DHCPRelayProviderDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDHCPRelay not implemented")
}
func (UnimplementedDHCPRelayProviderServiceServer) GetDHCPRelayStatus(context.Context, *DHCPRelayProviderGetStatusRequest) (*DHCPRelayProviderGetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDHCPRelayStatus not implemented")
}
func (UnimplementedDHCPRelayProviderServiceServer) mustEmbedUnimplementedDHCPRelayProviderServiceServer() {
}
func (UnimplementedDHCPRelayProviderServiceServer) testEmbeddedByValue() {}

// UnsafeDHCPRelayProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DHCPRelayProviderServiceServer will
// result in compilation errors.
type UnsafeDHCPRelayProviderServiceServer interface {
	mustEmbedUnimplementedDHCPRelayProviderServiceServer()
}

func RegisterDHCPRelayProviderServiceServer(s grpc.ServiceRegistrar, srv DHCPRelayProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedDHCPRelayProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DHCPRelayProviderService_ServiceDesc, srv)
}

func _DHCPRelayProviderService_EnsureDHCPRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHCPRelayProviderEnsureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHCPRelayProviderServiceServer).EnsureDHCPRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHCPRelayProviderService_EnsureDHCPRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHCPRelayProviderServiceServer).EnsureDHCPRelay(ctx, req.(*DHCPRelayProviderEnsureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHCPRelayProviderService_DeleteDHCPRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHCPRelayProviderDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHCPRelayProviderServiceServer).DeleteDHCPRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHCPRelayProviderService_DeleteDHCPRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHCPRelayProviderServiceServer).DeleteDHCPRelay(ctx, req.(*DHCPRelayProviderDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHCPRelayProviderService_GetDHCPRelayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHCPRelayProviderGetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHCPRelayProviderServiceServer).GetDHCPRelayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHCPRelayProviderService_GetDHCPRelayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHCPRelayProviderServiceServer).GetDHCPRelayStatus(ctx, req.(*DHCPRelayProviderGetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DHCPRelayProviderService_ServiceDesc is the grpc.ServiceDesc for DHCPRelayProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DHCPRelayProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.DHCPRelayProviderService",
	HandlerType: (*DHCPRelayProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureDHCPRelay",
			Handler:    _DHCPRelayProviderService_EnsureDHCPRelay_Handler,
		},
		{
			MethodName: "DeleteDHCPRelay",
			Handler:    _DHCPRelayProviderService_DeleteDHCPRelay_Handler,
		},
		{
			MethodName: "GetDHCPRelayStatus",
			Handler:    _DHCPRelayProviderService_GetDHCPRelayStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}

const (
	VLANProviderService_EnsureVLAN_FullMethodName    = "/switchagent.v1.VLANProviderService/EnsureVLAN"
	VLANProviderService_DeleteVLAN_FullMethodName    = "/switchagent.v1.VLANProviderService/DeleteVLAN"
	VLANProviderService_GetVLANStatus_FullMethodName = "/switchagent.v1.VLANProviderService/GetVLANStatus"
)

// VLANProviderServiceClient is the client API for VLANProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VLANProviderServiceClient interface {
	EnsureVLAN(ctx context.Context, in *VLANProviderEnsureRequest, opts ...grpc.CallOption) (*VLANProviderEnsureResponse, error)
	DeleteVLAN(ctx context.Context, in *VLANProviderDeleteRequest, opts ...grpc.CallOption) (*VLANProviderDeleteResponse, error)
	GetVLANStatus(ctx context.Context, in *VLANProviderGetStatusRequest, opts ...grpc.CallOption) (*VLANProviderGetStatusResponse, error)
}

type vLANProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVLANProviderServiceClient(cc grpc.ClientConnInterface) VLANProviderServiceClient {
	return &vLANProviderServiceClient{cc}
}

func (c *vLANProviderServiceClient) EnsureVLAN(ctx context.Context, in *VLANProviderEnsureRequest, opts ...grpc.CallOption) (*VLANProviderEnsureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VLANProviderEnsureResponse)
	err := c.cc.Invoke(ctx, VLANProviderService_EnsureVLAN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vLANProviderServiceClient) DeleteVLAN(ctx context.Context, in *VLANProviderDeleteRequest, opts ...grpc.CallOption) (*VLANProviderDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VLANProviderDeleteResponse)
	err := c.cc.Invoke(ctx, VLANProviderService_DeleteVLAN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vLANProviderServiceClient) GetVLANStatus(ctx context.Context, in *VLANProviderGetStatusRequest, opts ...grpc.CallOption) (*VLANProviderGetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VLANProviderGetStatusResponse)
	err := c.cc.Invoke(ctx, VLANProviderService_GetVLANStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VLANProviderServiceServer is the server API for VLANProviderService service.
// All implementations must embed UnimplementedVLANProviderServiceServer
// for forward compatibility.
type VLANProviderServiceServer interface {
	EnsureVLAN(context.Context, *VLANProviderEnsureRequest) (*VLANProviderEnsureResponse, error)
	DeleteVLAN(context.Context, *VLANProviderDeleteRequest) (*VLANProviderDeleteResponse, error)
	GetVLANStatus(context.Context, *VLANProviderGetStatusRequest) (*VLANProviderGetStatusResponse, error)
	mustEmbedUnimplementedVLANProviderServiceServer()
}

// UnimplementedVLANProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVLANProviderServiceServer struct{}

func (UnimplementedVLANProviderServiceServer) EnsureVLAN(context.Context, *VLANProviderEnsureRequest) (*VLANProviderEnsureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureVLAN not implemented")
}
func (UnimplementedVLANProviderServiceServer) DeleteVLAN(context.Context, *VLANProviderDeleteRequest) (*VLANProviderDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVLAN not implemented")
}
func (UnimplementedVLANProviderServiceServer) GetVLANStatus(context.Context, *VLANProviderGetStatusRequest) (*VLANProviderGetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVLANStatus not implemented")
}
func (UnimplementedVLANProviderServiceServer) mustEmbedUnimplementedVLANProviderServiceServer() {}
func (UnimplementedVLANProviderServiceServer) testEmbeddedByValue()                             {}

// UnsafeVLANProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VLANProviderServiceServer will
// result in compilation errors.
type UnsafeVLANProviderServiceServer interface {
	mustEmbedUnimplementedVLANProviderServiceServer()
}

func RegisterVLANProviderServiceServer(s grpc.ServiceRegistrar, srv VLANProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedVLANProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VLANProviderService_ServiceDesc, srv)
}

func _VLANProviderService_EnsureVLAN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VLANProviderEnsureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VLANProviderServiceServer).EnsureVLAN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VLANProviderService_EnsureVLAN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VLANProviderServiceServer).EnsureVLAN(ctx, req.(*VLANProviderEnsureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VLANProviderService_DeleteVLAN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VLANProviderDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VLANProviderServiceServer).DeleteVLAN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VLANProviderService_DeleteVLAN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VLANProviderServiceServer).DeleteVLAN(ctx, req.(*VLANProviderDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VLANProviderService_GetVLANStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VLANProviderGetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VLANProviderServiceServer).GetVLANStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VLANProviderService_GetVLANStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VLANProviderServiceServer).GetVLANStatus(ctx, req.(*VLANProviderGetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VLANProviderService_ServiceDesc is the grpc.ServiceDesc for VLANProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VLANProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.VLANProviderService",
	HandlerType: (*VLANProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureVLAN",
			Handler:    _VLANProviderService_EnsureVLAN_Handler,
		},
		{
			MethodName: "DeleteVLAN",
			Handler:    _VLANProviderService_DeleteVLAN_Handler,
		},
		{
			MethodName: "GetVLANStatus",
			Handler:    _VLANProviderService_GetVLANStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}

const (
	LLDPProviderService_EnsureLLDP_FullMethodName    = "/switchagent.v1.LLDPProviderService/EnsureLLDP"
	LLDPProviderService_DeleteLLDP_FullMethodName    = "/switchagent.v1.LLDPProviderService/DeleteLLDP"
	LLDPProviderService_GetLLDPStatus_FullMethodName = "/switchagent.v1.LLDPProviderService/GetLLDPStatus"
)

// LLDPProviderServiceClient is the client API for LLDPProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLDPProviderServiceClient interface {
	EnsureLLDP(ctx context.Context, in *LLDPProviderEnsureRequest, opts ...grpc.CallOption) (*LLDPProviderEnsureResponse, error)
	DeleteLLDP(ctx context.Context, in *LLDPProviderDeleteRequest, opts ...grpc.CallOption) (*LLDPProviderDeleteResponse, error)
	GetLLDPStatus(ctx context.Context, in *LLDPProviderGetStatusRequest, opts ...grpc.CallOption) (*LLDPProviderGetStatusResponse, error)
}

type lLDPProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLDPProviderServiceClient(cc grpc.ClientConnInterface) LLDPProviderServiceClient {
	return &lLDPProviderServiceClient{cc}
}

func (c *lLDPProviderServiceClient) EnsureLLDP(ctx context.Context, in *LLDPProviderEnsureRequest, opts ...grpc.CallOption) (*LLDPProviderEnsureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLDPProviderEnsureResponse)
	err := c.cc.Invoke(ctx, LLDPProviderService_EnsureLLDP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLDPProviderServiceClient) DeleteLLDP(ctx context.Context, in *LLDPProviderDeleteRequest, opts ...grpc.CallOption) (*LLDPProviderDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLDPProviderDeleteResponse)
	err := c.cc.Invoke(ctx, LLDPProviderService_DeleteLLDP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLDPProviderServiceClient) GetLLDPStatus(ctx context.Context, in *LLDPProviderGetStatusRequest, opts ...grpc.CallOption) (*LLDPProviderGetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLDPProviderGetStatusResponse)
	err := c.cc.Invoke(ctx, LLDPProviderService_GetLLDPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLDPProviderServiceServer is the server API for LLDPProviderService service.
// All implementations must embed UnimplementedLLDPProviderServiceServer
// for forward compatibility.
type LLDPProviderServiceServer interface {
	EnsureLLDP(context.Context, *LLDPProviderEnsureRequest) (*LLDPProviderEnsureResponse, error)
	DeleteLLDP(context.Context, *LLDPProviderDeleteRequest) (*LLDPProviderDeleteResponse, error)
	GetLLDPStatus(context.Context, *LLDPProviderGetStatusRequest) (*LLDPProviderGetStatusResponse, error)
	mustEmbedUnimplementedLLDPProviderServiceServer()
}

// UnimplementedLLDPProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLDPProviderServiceServer struct{}

func (UnimplementedLLDPProviderServiceServer) EnsureLLDP(context.Context, *LLDPProviderEnsureRequest) (*LLDPProviderEnsureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureLLDP not implemented")
}
func (UnimplementedLLDPProviderServiceServer) DeleteLLDP(context.Context, *LLDPProviderDeleteRequest) (*LLDPProviderDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLLDP not implemented")
}
func (UnimplementedLLDPProviderServiceServer) GetLLDPStatus(context.Context, *LLDPProviderGetStatusRequest) (*LLDPProviderGetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLLDPStatus not implemented")
}
func (UnimplementedLLDPProviderServiceServer) mustEmbedUnimplementedLLDPProviderServiceServer() {}
func (UnimplementedLLDPProviderServiceServer) testEmbeddedByValue()                             {}

// UnsafeLLDPProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLDPProviderServiceServer will
// result in compilation errors.
type UnsafeLLDPProviderServiceServer interface {
	mustEmbedUnimplementedLLDPProviderServiceServer()
}

func RegisterLLDPProviderServiceServer(s grpc.ServiceRegistrar, srv LLDPProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedLLDPProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLDPProviderService_ServiceDesc, srv)
}

func _LLDPProviderService_EnsureLLDP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLDPProviderEnsureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLDPProviderServiceServer).EnsureLLDP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLDPProviderService_EnsureLLDP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLDPProviderServiceServer).EnsureLLDP(ctx, req.(*LLDPProviderEnsureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLDPProviderService_DeleteLLDP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLDPProviderDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLDPProviderServiceServer).DeleteLLDP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLDPProviderService_DeleteLLDP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLDPProviderServiceServer).DeleteLLDP(ctx, req.(*LLDPProviderDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLDPProviderService_GetLLDPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLDPProviderGetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLDPProviderServiceServer).GetLLDPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLDPProviderService_GetLLDPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLDPProviderServiceServer).GetLLDPStatus(ctx, req.(*LLDPProviderGetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLDPProviderService_ServiceDesc is the grpc.ServiceDesc for LLDPProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLDPProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.LLDPProviderService",
	HandlerType: (*LLDPProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureLLDP",
			Handler:    _LLDPProviderService_EnsureLLDP_Handler,
		},
		{
			MethodName: "DeleteLLDP",
			Handler:    _LLDPProviderService_DeleteLLDP_Handler,
		},
		{
			MethodName: "GetLLDPStatus",
			Handler:    _LLDPProviderService_GetLLDPStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}

const (
	WireSonicSwitchService_GetDevice_FullMethodName              = "/switchagent.v1.WireSonicSwitchService/GetDevice"
	WireSonicSwitchService_ApplySwitch_FullMethodName            = "/switchagent.v1.WireSonicSwitchService/ApplySwitch"
	WireSonicSwitchService_DeleteSwitch_FullMethodName           = "/switchagent.v1.WireSonicSwitchService/DeleteSwitch"
	WireSonicSwitchService_GetCellStatus_FullMethodName          = "/switchagent.v1.WireSonicSwitchService/GetCellStatus"
	WireSonicSwitchService_GetInterface_FullMethodName           = "/switchagent.v1.WireSonicSwitchService/GetInterface"
	WireSonicSwitchService_GetInterfaceState_FullMethodName      = "/switchagent.v1.WireSonicSwitchService/GetInterfaceState"
	WireSonicSwitchService_SetInterfaceAdminState_FullMethodName = "/switchagent.v1.WireSonicSwitchService/SetInterfaceAdminState"
	WireSonicSwitchService_ListInterfacesV2_FullMethodName       = "/switchagent.v1.WireSonicSwitchService/ListInterfacesV2"
)

// WireSonicSwitchServiceClient is the client API for WireSonicSwitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WireSonicSwitchService manages SONiC switch configuration via gRPC.
type WireSonicSwitchServiceClient interface {
	// GetDevice returns the provider-internal ID for a named device.
	GetDevice(ctx context.Context, in *WireGetDeviceRequest, opts ...grpc.CallOption) (*WireGetDeviceResponse, error)
	// ApplySwitch atomically applies a full switch configuration.
	ApplySwitch(ctx context.Context, in *ApplySwitchRequest, opts ...grpc.CallOption) (*ApplySwitchResponse, error)
	// DeleteSwitch removes all switch configuration from the named device.
	DeleteSwitch(ctx context.Context, in *DeleteSwitchRequest, opts ...grpc.CallOption) (*DeleteSwitchResponse, error)
	// GetCellStatus returns the provisioning state recorded by the last ApplySwitch call.
	GetCellStatus(ctx context.Context, in *GetCellStatusRequest, opts ...grpc.CallOption) (*GetCellStatusResponse, error)
	// GetInterface returns the provider-internal ID for a named interface.
	GetInterface(ctx context.Context, in *WireGetInterfaceRequest, opts ...grpc.CallOption) (*WireGetInterfaceResponse, error)
	// GetInterfaceState returns the current operational state of an interface.
	GetInterfaceState(ctx context.Context, in *WireGetInterfaceStateRequest, opts ...grpc.CallOption) (*WireGetInterfaceStateResponse, error)
	// SetInterfaceAdminState sets the admin state (up/down) of an interface.
	SetInterfaceAdminState(ctx context.Context, in *WireSetInterfaceAdminStateRequest, opts ...grpc.CallOption) (*WireSetInterfaceAdminStateResponse, error)
	// ListInterfaces returns the names of all interfaces known to the switch.
	ListInterfacesV2(ctx context.Context, in *ListInterfacesRequestV2, opts ...grpc.CallOption) (*ListInterfacesResponseV2, error)
}

type wireSonicSwitchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireSonicSwitchServiceClient(cc grpc.ClientConnInterface) WireSonicSwitchServiceClient {
	return &wireSonicSwitchServiceClient{cc}
}

func (c *wireSonicSwitchServiceClient) GetDevice(ctx context.Context, in *WireGetDeviceRequest, opts ...grpc.CallOption) (*WireGetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireGetDeviceResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) ApplySwitch(ctx context.Context, in *ApplySwitchRequest, opts ...grpc.CallOption) (*ApplySwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySwitchResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_ApplySwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) DeleteSwitch(ctx context.Context, in *DeleteSwitchRequest, opts ...grpc.CallOption) (*DeleteSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSwitchResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_DeleteSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) GetCellStatus(ctx context.Context, in *GetCellStatusRequest, opts ...grpc.CallOption) (*GetCellStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellStatusResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetCellStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) GetInterface(ctx context.Context, in *WireGetInterfaceRequest, opts ...grpc.CallOption) (*WireGetInterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireGetInterfaceResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) GetInterfaceState(ctx context.Context, in *WireGetInterfaceStateRequest, opts ...grpc.CallOption) (*WireGetInterfaceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireGetInterfaceStateResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_GetInterfaceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) SetInterfaceAdminState(ctx context.Context, in *WireSetInterfaceAdminStateRequest, opts ...grpc.CallOption) (*WireSetInterfaceAdminStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WireSetInterfaceAdminStateResponse)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_SetInterfaceAdminState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireSonicSwitchServiceClient) ListInterfacesV2(ctx context.Context, in *ListInterfacesRequestV2, opts ...grpc.CallOption) (*ListInterfacesResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterfacesResponseV2)
	err := c.cc.Invoke(ctx, WireSonicSwitchService_ListInterfacesV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireSonicSwitchServiceServer is the server API for WireSonicSwitchService service.
// All implementations must embed UnimplementedWireSonicSwitchServiceServer
// for forward compatibility.
//
// WireSonicSwitchService manages SONiC switch configuration via gRPC.
type WireSonicSwitchServiceServer interface {
	// GetDevice returns the provider-internal ID for a named device.
	GetDevice(context.Context, *WireGetDeviceRequest) (*WireGetDeviceResponse, error)
	// ApplySwitch atomically applies a full switch configuration.
	ApplySwitch(context.Context, *ApplySwitchRequest) (*ApplySwitchResponse, error)
	// DeleteSwitch removes all switch configuration from the named device.
	DeleteSwitch(context.Context, *DeleteSwitchRequest) (*DeleteSwitchResponse, error)
	// GetCellStatus returns the provisioning state recorded by the last ApplySwitch call.
	GetCellStatus(context.Context, *GetCellStatusRequest) (*GetCellStatusResponse, error)
	// GetInterface returns the provider-internal ID for a named interface.
	GetInterface(context.Context, *WireGetInterfaceRequest) (*WireGetInterfaceResponse, error)
	// GetInterfaceState returns the current operational state of an interface.
	GetInterfaceState(context.Context, *WireGetInterfaceStateRequest) (*WireGetInterfaceStateResponse, error)
	// SetInterfaceAdminState sets the admin state (up/down) of an interface.
	SetInterfaceAdminState(context.Context, *WireSetInterfaceAdminStateRequest) (*WireSetInterfaceAdminStateResponse, error)
	// ListInterfaces returns the names of all interfaces known to the switch.
	ListInterfacesV2(context.Context, *ListInterfacesRequestV2) (*ListInterfacesResponseV2, error)
	mustEmbedUnimplementedWireSonicSwitchServiceServer()
}

// UnimplementedWireSonicSwitchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireSonicSwitchServiceServer struct{}

func (UnimplementedWireSonicSwitchServiceServer) GetDevice(context.Context, *WireGetDeviceRequest) (*WireGetDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) ApplySwitch(context.Context, *ApplySwitchRequest) (*ApplySwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySwitch not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) DeleteSwitch(context.Context, *DeleteSwitchRequest) (*DeleteSwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSwitch not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) GetCellStatus(context.Context, *GetCellStatusRequest) (*GetCellStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCellStatus not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) GetInterface(context.Context, *WireGetInterfaceRequest) (*WireGetInterfaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterface not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) GetInterfaceState(context.Context, *WireGetInterfaceStateRequest) (*WireGetInterfaceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfaceState not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) SetInterfaceAdminState(context.Context, *WireSetInterfaceAdminStateRequest) (*WireSetInterfaceAdminStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInterfaceAdminState not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) ListInterfacesV2(context.Context, *ListInterfacesRequestV2) (*ListInterfacesResponseV2, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterfacesV2 not implemented")
}
func (UnimplementedWireSonicSwitchServiceServer) mustEmbedUnimplementedWireSonicSwitchServiceServer() {
}
func (UnimplementedWireSonicSwitchServiceServer) testEmbeddedByValue() {}

// UnsafeWireSonicSwitchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireSonicSwitchServiceServer will
// result in compilation errors.
type UnsafeWireSonicSwitchServiceServer interface {
	mustEmbedUnimplementedWireSonicSwitchServiceServer()
}

func RegisterWireSonicSwitchServiceServer(s grpc.ServiceRegistrar, srv WireSonicSwitchServiceServer) {
	// If the following call panics, it indicates UnimplementedWireSonicSwitchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireSonicSwitchService_ServiceDesc, srv)
}

func _WireSonicSwitchService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireGetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetDevice(ctx, req.(*WireGetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_ApplySwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).ApplySwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_ApplySwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).ApplySwitch(ctx, req.(*ApplySwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_DeleteSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).DeleteSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_DeleteSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).DeleteSwitch(ctx, req.(*DeleteSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_GetCellStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetCellStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetCellStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetCellStatus(ctx, req.(*GetCellStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_GetInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireGetInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetInterface(ctx, req.(*WireGetInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_GetInterfaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireGetInterfaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).GetInterfaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_GetInterfaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).GetInterfaceState(ctx, req.(*WireGetInterfaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_SetInterfaceAdminState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireSetInterfaceAdminStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).SetInterfaceAdminState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_SetInterfaceAdminState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).SetInterfaceAdminState(ctx, req.(*WireSetInterfaceAdminStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireSonicSwitchService_ListInterfacesV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterfacesRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireSonicSwitchServiceServer).ListInterfacesV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireSonicSwitchService_ListInterfacesV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireSonicSwitchServiceServer).ListInterfacesV2(ctx, req.(*ListInterfacesRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

// WireSonicSwitchService_ServiceDesc is the grpc.ServiceDesc for WireSonicSwitchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireSonicSwitchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "switchagent.v1.WireSonicSwitchService",
	HandlerType: (*WireSonicSwitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevice",
			Handler:    _WireSonicSwitchService_GetDevice_Handler,
		},
		{
			MethodName: "ApplySwitch",
			Handler:    _WireSonicSwitchService_ApplySwitch_Handler,
		},
		{
			MethodName: "DeleteSwitch",
			Handler:    _WireSonicSwitchService_DeleteSwitch_Handler,
		},
		{
			MethodName: "GetCellStatus",
			Handler:    _WireSonicSwitchService_GetCellStatus_Handler,
		},
		{
			MethodName: "GetInterface",
			Handler:    _WireSonicSwitchService_GetInterface_Handler,
		},
		{
			MethodName: "GetInterfaceState",
			Handler:    _WireSonicSwitchService_GetInterfaceState_Handler,
		},
		{
			MethodName: "SetInterfaceAdminState",
			Handler:    _WireSonicSwitchService_SetInterfaceAdminState_Handler,
		},
		{
			MethodName: "ListInterfacesV2",
			Handler:    _WireSonicSwitchService_ListInterfacesV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/agent/proto/switch_agent.proto",
}
